### PR TITLE
Significant Updates to Bots and Referrer Lists

### PR DESCRIPTION
**Pull request by davcpas1234**
@mitchellkrogza another set of updates from me.

I also have these user-agents that are **trying** to do some nasty things (vulnerability checks, multiple wp-admin, phpmyadmin and xml requests etc.). Your thoughts on adding:
- curl/`<Version>`
- Python-urllib
- python-requests

Also, what's your thoughts on `archive.org_bot`?

**EDIT:**
I've added a large update to `bad-user-agents.list` based on a collation of lists of reportedly "dis-reputable" bots and sites. Your feedback is welcomed 😄

### CODE REVIEW

**Comment by davcpas1234** [comment]
Thinking it's probably a "bad" idea to bad the curl/py UA's globally as these may be needed by some. I'll probably add these to my internal list as a separate.

**Comment by davcpas1234** [comment]
Also found an interesting UA, your thoughts? (This is definitely the UA, not referrer)

```
http://www.nominet.org.uk/privacypolicy
```

**Comment by mitchellkrogza** [comment]
Thanks @davcpas1234 I will have to check through this but so far looks good, couple of small things I must check

**Comment by mitchellkrogza** [comment]
@davcpas1234 just remember we use
`BrowserMatchNoCase` & `SetEnvIfNoCase Referer` so duplicates like  `aihitbot` `aipbot` etc etc are already covered because we don't pay attention to case sensitivity.

**Comment by davcpas1234** [comment]
@mitchellkrogza Indeed, the casing is a result of my duplicate filtering from my lists. Apologies for any additional work required for you.

**Comment by mitchellkrogza** [comment]
Morning @davcpas1234 just doing a dupe cleanup and will modify your committed list with the complete sorted list, the generator scripts will handle any dupes thereafter.

**Comment by mitchellkrogza** [comment]
@davcpas1234 some agents like
```
curl/<Version>
Python-urllib
python-requests
Java
```

Are often used by people for good / also monitoring so blocking them across the board will cause big issues for some people on next update. Happened once before with adding user-agent `Java` (I think) which caused major upset to some users.

**Comment by mitchellkrogza** [comment]
Just thought I would share why `python-requests` should not be blocked and was removed from this commit. It is used by bidswitchbot which is somehow linked to ad networks, I use Google Ads on many sites so I often see this type of request and it's the same IP, first request uses the agent `python-requests` and then `bidswitchbot` looking for an ads.txt file.

```
*.*.*.* - - * [04/Sep/2018:13:50:23 +0200] "GET /robots.txt HTTP/1.1" 200 55 "-" "python-requests/2.12.5" "-"PORT:443 0.000 - . "GZIP:0.55"
*.*.*.* - - * [04/Sep/2018:13:50:24 +0200] "GET /ads.txt HTTP/1.1" 200 89 "-" "bidswitchbot/1.0" "-"PORT:443 0.000 - . "GZIP:0.74"
```

**Pull request merged**
