### PR TITLE
adding backup true or false option

### PR DESCRIPTION
**Pull request by lutaylor**

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
@lutaylor what do you think about one or two curl tests in the update script which can check for a proper functioning blocker after each update and also reveal to a user if any custom configurations have caused a mishap?

**Comment by lutaylor** [comment]
@mitchellkrogza 
Good idea I am just wondering how to handle SSL. 
e.g. https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/.dev-tools/run-curl-tests-2.4.sh#L38 
 
That would work for HTTP fine but if the server was set to use only HTTPS it would fail.

**Comment by mitchellkrogza** [comment]
@lutaylor maybe if we have a user option in the update file
```
TEST_BEFORE_RELOAD=True
TEST_WITH=https
TEST_URL=mysite.com
```

**Comment by mitchellkrogza** [comment]
@lutaylor Update Tests on both Apache 2.2 and 2.4 added today into the TravisCI checks. Had to do some sed replacements for the 2.2 version which works.

**Comment by lutaylor** [comment]
@mitchellkrogza 
Not a bad idea! I will implement something like that.  

BTW its "Luke Taylor" not "Lu Taylor" :)

**Comment by mitchellkrogza** [comment]
Great Luke 😉  I will update your name on the Readme

**Comment by lutaylor** [comment]
@mitchellkrogza 
Here you go https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/pull/94

**Pull request merged**
