### PR TITLE
Add customs spam referrer to Apache 2.4

### PR DESCRIPTION
**Pull request by eldk**
Hello,

Try to had custom bad referer or hotlink referer list.

Thanks,

Eric

PS : I can't test it for Apache 2.2 so I haven't modified anything for it

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Introducing a new include would cause an outage for existing users who pull an update and then sit with a missing file error. Going to need to test this one another server to see how it reacts with a missing include file.

**Comment by eldk** [comment]
Hello,
Maybe the include should be commented, and some doc added to alert users on the fact they should uncommented it if they want to had their own "hotlinker" or spam_referer ?

**Comment by mitchellkrogza** [comment]
Problem with that is if they uncomment it on the next update it will be commented out again. I need to look into a better update script as we have with the Nginx blocker.

**Comment by mitchellkrogza** [comment]
Unfortunately a missing include causes Apache to fail reloading.

The existing `custom.d/bad-referrer-words.conf` can be used for this same purpose.

**Comment by mitchellkrogza** [comment]
@eldk default include files updated with better commenting in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/b54876a643bf98b3c80750fe811a9056c6df5620

**Pull request closed without merging**
