### PR TITLE
Update IPs as per email from cloudflare

### PR DESCRIPTION
**Pull request by GervaisdeM**
See:
https://www.cloudflare.com/en-ca/ips/
(Updated Apr 8, 2021)

### CODE REVIEW

**Comment by GervaisdeM** [comment]
@mitchellkrogza I see that there are some files in `.dev-tools` where the IP ranges in question are also listed. I can update those also if that is required.

Also editor-config automatically fixed a bunch of trailing whitespace in this PR.
Those changes can be hidden with:
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/pull/155/files?w=1

**Comment by GervaisdeM** [comment]
@mitchellkrogza See my question above from a couple of weeks ago?

**Comment by mitchellkrogza** [comment]
Hi @GervaisdeM sorry been a bit busy and fallen behind on email. Happy with these changes but they need to made in
```.dev-tools/apache2.2.template
.dev-tools/apache2.4.template
.dev-tools/centos6.template
.dev-tools/centos7.template```
otherwise they will just get overwritten by the generator

Similarly the changes to Cloudflare needs to be done in _generator_lists/cloudflare-ip-ranges.list and the generator will take care of generating all new lists from the generator input files.

**Comment by GervaisdeM** [comment]
I updated
```
.dev-tools/apache2.2.template
.dev-tools/apache2.4.template
_generator_lists/cloudflare-ip-ranges.list
```

These files don't exist
```
.dev-tools/centos6.template
.dev-tools/centos7.template
```

The ip range that is being dropped does still appear in the following files. Not certain if they should also be updated:
```
.dev-tools/_conf_files_for_testing/apache2.4.34/old-globalblacklist.conf
.dev-tools/_conf_files_for_testing/apache2.2.25/old-globalblacklist.conf
.dev-tools/_test_results/_conf_files_2.2/globalblacklist.conf
.dev-tools/_test_results/_conf_files_2.4/globalblacklist.conf
.dev-tools/_deprecated/apache2.4.template.centos
.dev-tools/_deprecated/CentOS7/custom.d/globalblacklist.conf
.dev-tools/_deprecated/CentOS6/conf.d/globalblacklist.conf
.dev-tools/_deprecated/centos7.template
.dev-tools/_deprecated/centos6.template
```

**Comment by mitchellkrogza** [comment]
Thanks @GervaisdeM merged. No need to update any templates deprecated or for testing

**Pull request merged**
