### PR TITLE
Attempting to fix Travis check

### PR DESCRIPTION
**Pull request by lutaylor**

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
I sent a new commit as changes should have been in a different file but now this morning TravisCI is not starting builds, have tweeted them.

**Comment by mitchellkrogza** [comment]
I'll relook at this Monday let Travis get all their problems sorted first. Have an idea which I'll run through a test repo first and if successful I'll move it across to the main repo.

**Comment by mitchellkrogza** [comment]
Okay step 1 is complete, I am now building 2.2.25 and testing properly against it. I realised a big error where I was running the 2.2 tests against 2.4.x actually. That's now sorted and tests pass so now onto step 2 of building 2.4.34 and running tests against that.

**Comment by mitchellkrogza** [comment]
@lutaylor okay all Apache 2.2 and 2.4 versions now sorted.
- Apache 2.2 All test pass ✔️ 
- Apache 2.4 tests pass (with access_compat) enabled ✔️ 
- Apache 2.4 tests fail (with access_compat) disabled) 🔴 

Our differences/trouble lies somewhere herein (below) but now my mind is tired today after the big cleanup and fixes.

Current <RequireAny> configuration for 2.4
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/.dev-tools/apache2.4.template#L7207-L7397

Previous Working Configuration of <RequireAny> for 2.4 which caused users headaches but made Travis pass
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/.dev-tools/_deprecated/apache2.4.template.travis-test-passer#L6294-L6477

Maybe you can spot the problem at least now all tests are running on the correct versions of Apache so that issue is out the way.

The files needing to be scrutinized are:

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/.dev-tools/_conf_files_for_testing/apache2.4.34/000-default.conf

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/.dev-tools/_conf_files_for_testing/apache2.4.34/apache2.conf

and of course then the differences in the <RequireAny> Blocks .... somewhere I am missing something staring me in the face :joy:

**Comment by mitchellkrogza** [comment]
@lutaylor I must reiterate again I am running the current 2.4 version of the blocker on an Ubuntu 16.04 server with access_compat disabled and it passes all tests. Only difference is (I think) is that the version of 2.4 on Ubuntu now from the repos is 2. 4.15 or thereabouts and inside Travis we are testing with 2.4.34 but I should hope that's not the problem.

**Comment by lutaylor** [comment]
@mitchellkrogza 
Np glad to help!

**Comment by mitchellkrogza** [comment]
We also now have a new branch for testing anything obscure now without breaking the master branch. So a lot of good came from this.

**Pull request merged**
